### ISSUE TITLE
Create index

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-MongoDB-Sink-Connector#5]
In order to improve query performance, we can create indexes on
- user
- source
- start
- end

MongoDb automatically indexes only `_id`.

@sboettcher has reported up to `30sec` latency while requesting `get_all_subjects_json` on `REST-Api` and CPU usage to 100% for MongoDb container process. `get_all_subjects_json` function relays on two queries based on `distinct`.

**Comment by sboettcher** [comment]
I am also now frequently getting 504 Gateway Time-out, even when just requesting last_received_sample, when querying multiple requests in parallel.

**Comment by yatharthranjan** [comment]
@afolarin was the indexing done? Or do we need to do it?

**Comment by afolarin** [comment]
As far as I remember all the indexing necessary to avoid the DISTINCT was done. This is though doesn't affect the FIND queries.

**Comment by afolarin** [comment]
closing
